server:
  servlet:
    context-path: /api

# Connection properties DB
app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/amigoscodedemo
    username: postgres
    password: password
    pool-size: 30